[package]
name = "fastnoise-simd"
version = "0.1.0"
authors = ["Austin Johnson <me@austinj.me>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastnoise_simd_bindings = { path = "../fastnoise-simd-bindings" }
